<?php
    $lang = [
        'dashboard' => 'Dashboard',
        'history' => 'History',
        'withdraw' => 'Withdraw',
        'settings' => 'Settings',		        'balance' => 'Balance',
        'admin' => 'admin',
        'site prefrences' => 'Site prefrences',
        'users management' => 'Users management',		        'logout' => 'Logout',		        'buy hashrate' => 'Buy Hashrate',		        'copyrights' => 'All Rights Reserved.',		        'last' => 'Last',		        'payout' => 'Payout',		        'hashrate' => 'Hashrate',		        'pools' => 'Pools',		        'revenue' => 'Revenue',		        'per' => 'per',				'revenue forcast' => 'Revenue forecast',				'items' => 'Items',				'quantity' => 'Quantity',				'unit price' => 'Unit Price',				'total price' => 'Total Price',				'total' => 'Total',				'select payment method' => 'Select payment method',				'update' => 'Update',				'cancel' => 'Cancel',				'close' => 'Close',				'choose currency' => 'Choose currency',				'transaction rule' => 'Please dont forget about your wallets commission when transferring the funds (we recommend checking the exact commission with your wallet provider). ',				'please transfer' => 'Please transfer',				'to' => 'To',				'to finalize your purchase' => 'to finalize your purchase.',				'status' => 'Status',				'timeout' => 'Timeout',				'package bought with' => 'Package bought with',				'with balance' => 'With Balance',				'packages' => 'Packages',				'method' => 'Method',				'product' => 'Product',				'time' => 'Time',				'transaction' => 'Transaction',				'view transaction' => 'View Transaction',				'previous' => 'Previous',				'withdrawals' => 'Withdrawals',				'amount' => 'Amount',				'currency' => 'Currency',				'is approved' => 'Is Approved',				'log' => 'Log',				'description' => 'Description',				'profile' => 'Profile',				'email' => 'Email',				'avatar' => 'Avatar',				'wallet' => 'Wallet',				'make sure btc' => 'Make sure the address is a real BTC address',				'make sure eth' => 'Make sure the address is a real ETH address',				'make sure dash' => 'Make sure the address is a real DASH address',				'make sure zec' => 'Make sure the address is a real ZEC address',				'contact details' => 'Contact Details',			'change password' => 'Change Password',				'password' => 'Password',				'first name' => 'First name',				'last name' => 'last name',				'company' => 'Company',				'company code' => 'Company Code',				'phone number' => 'Phone number',				'repeat' => 'Repeat',				'address' => 'Address',				'city' => 'City',				'region' => 'Region',				'country' => 'Country',				'postal code' => 'Postal Code',				'request' => 'Request'												
    ]
?>